name: BobbiKlein
favicon: null
layout_spectrum: 0.904715487267822
typography_spectrum: 0.9049074267968535
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030106'
    - '#2a3c6a'
    - '#766591'
    - '#ff7c55'
    - '#efe5dc'
  brandStrength: 0.8125
  lightness: 0.9375
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
